POST http://localhost:5000/syoft/auth/register
Content-Type: application/json

{
    "username":"tharun",
    "email":"mintu@gmail.com",
    "password":"123456",
    "role":"staff"
}
###


POST http://localhost:5000/syoft/auth/login 
Content-Type: application/json

{
    "email":"tharun@gmail.com",
    "password":"123456"
}

###
POST http://localhost:5000/syoft/product
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRoYXJ1biIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTcyMTA0NDc1OH0.sbzBbX0ACM86j0lhLwNYpvLS3PyMmz7sp6qQfLc9Kw8

{
    "title":"Samsung",
    "description":"Apple iphone 15 Pro Max is launched in 2023",
    "inventryCount":20
}

###

GET http://localhost:5000/syoft/product
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRoYXJ1biIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTcyMTA0NDc1OH0.sbzBbX0ACM86j0lhLwNYpvLS3PyMmz7sp6qQfLc9Kw8

###

PUT http://localhost:5000/syoft/product/66950f9533a8ad0851cadae3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRoYXJ1biIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTcyMTA0NDc1OH0.sbzBbX0ACM86j0lhLwNYpvLS3PyMmz7sp6qQfLc9Kw8

{
    "description":"Samsung mobile phone was the india's no.1 mobile phone"
}


###

DELETE http://localhost:5000/syoft/product/66950f2833a8ad0851cadada
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRoYXJ1biIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTcyMTA0NDc1OH0.sbzBbX0ACM86j0lhLwNYpvLS3PyMmz7sp6qQfLc9Kw8
